name: Update Site

on:
  push:

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install js-yaml fs

      - name: Update _data/projects.yml
        run: node updateData.js
      
      - name: Commit changes
        run: |
          git config --local user.email "mkorcy@gmail.com"
          git commit -am "Update site"
          git push
